"""Generate the "bubble" CardGroup on each category index page from docs.json.

For every top-level nav group that has a `<prefix>/index` page, this writes a
CardGroup listing ALL of that group's sub-pages (nested groups flattened),
using each page's own frontmatter `title` so card labels always match the nav.

Cards are written between these markers in the index page:
    {/* CARDS_START ... */}
    {/* CARDS_END */}

Run from anywhere:  python .github/scripts/gen_cards.py
"""
import json
import re
from pathlib import Path

DOCS = Path(__file__).resolve().parents[2] / "docs"

START_RE = re.compile(r"\{/\* CARDS_START.*?\*/\}", re.S)
BLOCK_RE = re.compile(r"\{/\* CARDS_START.*?\{/\* CARDS_END \*/\}", re.S)


def frontmatter(slug):
    p = DOCS / (slug + ".mdx")
    if not p.exists():
        return (slug, "")
    text = p.read_text(encoding="utf-8")
    m = re.search(r"^---\s*(.*?)\s*---", text, re.S)
    blk = m.group(1) if m else ""
    title = re.search(r'^title:\s*"?(.*?)"?\s*$', blk, re.M)
    desc = re.search(r'^description:\s*"?(.*?)"?\s*$', blk, re.M)
    return (title.group(1) if title else slug, desc.group(1) if desc else "")


def flatten(pages):
    out = []
    for p in pages:
        if isinstance(p, str):
            out.append(p)
        elif isinstance(p, dict):
            out.extend(flatten(p["pages"]))
    return out


def main():
    nav = json.loads((DOCS / "docs.json").read_text(encoding="utf-8"))
    groups = nav["navigation"]["tabs"][0]["groups"][0]["pages"]

    updated = 0
    for g in groups:
        if not isinstance(g, dict):
            continue
        icon = g.get("icon", "")
        pages = flatten(g["pages"])
        index_pages = [p for p in pages if p.rsplit("/", 1)[-1] == "index"]
        if not index_pages:
            continue
        index_slug = index_pages[0]
        children = [p for p in pages if p != index_slug]
        index_file = DOCS / (index_slug + ".mdx")
        text = index_file.read_text(encoding="utf-8")
        if not START_RE.search(text):
            print(f"SKIP {index_slug}: no CARDS_START marker")
            continue

        lines = ["<CardGroup cols={2}>"]
        for child in children:
            title, desc = frontmatter(child)
            icon_attr = f' icon="{icon}"' if icon else ""
            lines.append(f'  <Card title="{title}" href="/{child}"{icon_attr}>')
            if desc:
                lines.append(f"    {desc}")
            lines.append("  </Card>")
        lines.append("</CardGroup>")
        cards = "\n".join(lines)

        replacement = (
            "{/* CARDS_START - generated by .github/scripts/gen_cards.py; do not edit by hand */}\n"
            + cards
            + "\n{/* CARDS_END */}"
        )
        new_text = BLOCK_RE.sub(lambda _m: replacement, text)
        if new_text != text:
            index_file.write_text(new_text, encoding="utf-8")
            updated += 1
            print(f"  {index_slug}: {len(children)} cards")

    print(f"Updated {updated} index pages.")


if __name__ == "__main__":
    main()
