#!/usr/bin/env python3
"""
Generate the repo CODEOWNERS from the real owners (not placeholders).

Two sources, kept in sync:
  1. docs/ pages - owner read from each page's hidden {/* owner: id */}
     header (the single source of truth for documentation pages).
  2. example directories - a static map (EXAMPLE_OWNERS) seeded from the
     2026 Ryzen AI content-owners sheet. These paths follow the upstream
     RyzenAI-SW example layout so ownership is correct after consolidation.

CODEOWNERS uses GitHub usernames only (emails are not valid there). Order:
default first, then infra, then example dirs, then specific docs pages last so
the most specific rule wins.

Run from anywhere:
    python .github/scripts/generate_codeowners.py
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs"
OUT = DOCS / "CODEOWNERS"  # GitHub also reads CODEOWNERS from docs/

DEFAULT_OWNER = "dwithchenna"   # per the proposal: Dwith Chenna is the default owner
INFRA_OWNER = "bconsolvo"       # docs lead owns CI/infra

OWNER_RE = re.compile(r"\{/\*\s*owner:\s*(?P<id>[^|*]+?)\s*(?:\|[^*]*)?\*/\}")

# Example-directory ownership (upstream RyzenAI-SW layout). Seeded from the
# content-owners sheet; edit here when example ownership changes.
EXAMPLE_OWNERS: list[tuple[str, str]] = [
    ("/CNN-examples/Nemotron-OCR-V2/", "lakshay048"),
    ("/CNN-examples/getting_started_resnet/", "dwithchenna"),
    ("/CNN-examples/getting_started_resnet/bf16/", "dwithchenna"),
    ("/CNN-examples/getting_started_resnet/int8/", "dwithchenna"),
    ("/CNN-examples/hello_world/", "dwithchenna"),
    ("/CNN-examples/hello_world/models/", "dwithchenna"),
    ("/CNN-examples/iGPU/getting_started/", "dwithchenna"),
    ("/CNN-examples/image_classification/", "dwithchenna"),
    ("/CNN-examples/object_detection/yolov8m/", "dwithchenna"),
    ("/CNN-examples/object_detection/yolov8s-worldv2/", "dwithchenna"),
    ("/CNN-examples/quark_quantization/", "dwithchenna"),
    ("/CNN-examples/super-resolution/", "bconsolvo"),
    ("/CNN-examples/torchvision_inference/", "dwithchenna"),
    ("/Demos/ASR/Parakeet-TDT/", "lakshay048"),
    ("/Demos/ASR/Whisper/", "dwithchenna"),
    ("/Demos/NPU-GPU-Pipeline/", "dwithchenna"),
    ("/LLM-examples/", "dwithchenna"),
    ("/LLM-examples/RAG-OGA/", "dwithchenna"),
    ("/LLM-examples/VLM/", "dwithchenna"),
    ("/LLM-examples/llm-sft-deploy/", "dwithchenna"),
    ("/LLM-examples/oga_api/", "dwithchenna"),
    ("/LLM-examples/oga_inference/", "dwithchenna"),
    ("/README.md", "dwithchenna"),
    ("/Ryzen-AI-CVML-Library/", "dwithchenna"),
    ("/Ryzen-AI-CVML-Library/samples/cvml-sample-face-detection/", "dwithchenna"),
    ("/Ryzen-AI-CVML-Library/samples/cvml-sample-face-mesh/", "dwithchenna"),
    ("/Transformer-examples/ASR/Whisper-AI/", "dwithchenna"),
    ("/Transformer-examples/DistilBERT_text_classification_bf16/", "dwithchenna"),
    ("/WinML/CNN/ResNet/", "dwithchenna"),
    ("/WinML/CNN/ResNet/cpp/", "dwithchenna"),
    ("/WinML/Transformers/GoogleBert/", "dwithchenna"),
    ("/WinML/Transformers/clip-vit-base-patch16/", "dwithchenna"),
    ("/onnx-benchmark/", "dwithchenna"),
    ("/utilities/npu_check/", "dwithchenna"),
]


def page_owner(path: Path) -> str:
    m = OWNER_RE.search(path.read_text(encoding="utf-8"))
    return m.group("id").strip() if m else DEFAULT_OWNER


def main() -> None:
    lines = [
        "# CODEOWNERS - Ryzen AI Software docs",
        "# Generated by .github/scripts/generate_codeowners.py from the in-page",
        "# owner headers (docs/) plus the static EXAMPLE_OWNERS map (examples).",
        "# Do not hand-edit; update the page header (or EXAMPLE_OWNERS) and regenerate.",
        "",
        "# Default owner",
        f"{'*':<55} @{DEFAULT_OWNER}",
        "",
        "# Docs infrastructure (CI / config) owned by the docs lead",
        f"{'/.github/':<55} @{INFRA_OWNER}",
        f"{'/docs/docs.json':<55} @{INFRA_OWNER}",
        "",
        "# Example directories (from content-owners sheet)",
    ]
    for path, gh in EXAMPLE_OWNERS:
        lines.append(f"{path:<55} @{gh}")

    lines += ["", "# Documentation pages (owner from each page's header)"]
    for mdx in sorted(DOCS.rglob("*.mdx")):
        rel = "/docs/" + mdx.relative_to(DOCS).as_posix()
        lines.append(f"{rel:<55} @{page_owner(mdx)}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
