#!/usr/bin/env python3
"""
Generate docs/CODEOWNERS from the ACTUAL docs tree - no external spreadsheet.

Ownership lives in each page as a hidden header (the single source of truth):

    {/* owner: <github-id> */}

This script walks every page under docs/ (`.mdx` AND `.md`) and emits, in order:

  1. a default owner (catch-all),
  2. infra rules (CI config) owned by the docs lead,
  3. one rule per top-level section folder, set to that folder's dominant owner,
  4. a per-page rule for every page (most specific - GitHub uses the LAST match).

There is intentionally NO hard-coded example/path map: CODEOWNERS always
reflects the current folder structure. Pages without an owner header fall back
to the default owner. Run from anywhere:

    python .github/scripts/generate_codeowners.py
"""

import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs"
OUT = DOCS / "CODEOWNERS"

DEFAULT_OWNER = "dwithchenna"   # catch-all owner for anything unmatched
INFRA_OWNER = "bconsolvo"       # docs lead owns CI / config

OWNER_RE = re.compile(r"\{/\*\s*owner:\s*(?P<id>[^|*]+?)\s*(?:\|[^*]*)?\*/\}")

COL = 56  # path column width for alignment


def page_owner(path: Path) -> str:
    try:
        m = OWNER_RE.search(path.read_text(encoding="utf-8"))
    except Exception:
        return DEFAULT_OWNER
    return m.group("id").strip() if m else DEFAULT_OWNER


def rule(path: str, owner: str) -> str:
    return f"{path:<{COL}} @{owner}"


def main() -> None:
    pages = sorted(
        set(DOCS.rglob("*.mdx")) | set(DOCS.rglob("*.md")),
        key=lambda p: p.relative_to(DOCS).as_posix(),
    )
    owners = {p: page_owner(p) for p in pages}

    # Top-level section folders -> dominant owner among their pages
    sections: dict[str, list[Path]] = {}
    top_pages: list[Path] = []
    for p in pages:
        rel_parts = p.relative_to(DOCS).parts
        if len(rel_parts) == 1:
            top_pages.append(p)              # docs/index.mdx, docs/installation.mdx, ...
        else:
            sections.setdefault(rel_parts[0], []).append(p)

    lines = [
        "# CODEOWNERS - Ryzen AI Software documentation",
        "# GENERATED by .github/scripts/generate_codeowners.py from each page's",
        "# hidden `{/* owner: <id> */}` header. Do NOT hand-edit: change the page",
        "# header (or add a page) and regenerate. GitHub uses the LAST matching",
        "# rule, so the per-page rules at the bottom override the folder defaults.",
        "",
        "# ----- Default owner (catch-all) -----",
        rule("*", DEFAULT_OWNER),
        "",
        "# ----- CI / configuration (docs lead) -----",
        rule("/.github/", INFRA_OWNER),
        rule("/docs/docs.json", INFRA_OWNER),
        "",
        "# ----- Section defaults (dominant owner per top-level folder) -----",
    ]
    for section in sorted(sections):
        dominant = Counter(owners[p] for p in sections[section]).most_common(1)[0][0]
        lines.append(rule(f"/docs/{section}/", dominant))

    lines += ["", "# ----- Top-level pages -----"]
    for p in sorted(top_pages, key=lambda p: p.name):
        lines.append(rule(f"/docs/{p.name}", owners[p]))

    for section in sorted(sections):
        lines += ["", f"# ----- {section}/ -----"]
        for p in sorted(sections[section], key=lambda p: p.relative_to(DOCS).as_posix()):
            lines.append(rule("/docs/" + p.relative_to(DOCS).as_posix(), owners[p]))

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_owners = len(set(owners.values()))
    print(f"Wrote {OUT} - {len(pages)} pages, {len(sections)} sections, {n_owners} distinct owners.")


if __name__ == "__main__":
    main()
