#!/usr/bin/env python3
"""
Build a readable per-page code-block report from a run's JSON results.

Input  : the --output-json file from extract_code_blocks.py (per-block records).
Outputs:
  - CODE_TEST_REPORT.md : a dashboard - summary table (one row per page) + a
    per-page detail table (one row per block: #, lang, result, short detail).
  - optionally injects the summary table into a Mintlify page between
    {/* RESULTS_START */} and {/* RESULTS_END */} (e.g. the CI dashboard page).

Covers EVERY .mdx and .md under --docs, including pages with zero code blocks
(shown as "no code"), so nothing is silently missing.

Usage:
  python .github/scripts/report.py --results report_run.json --docs docs \
      --out .github/scripts/CODE_TEST_REPORT.md \
      --dashboard docs/reference/ci-dashboard.mdx
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from resolve_owner import resolve  # noqa: E402

RUNNABLE = {"python", "bash", "sh", "shell", "powershell", "pwsh", "ps1",
            "cmd", "bat", "batch"}


def clean(detail: str, n: int = 90) -> str:
    s = re.sub(r"\s+", " ", (detail or "")).strip().replace("|", "\\|")
    return (s[:n] + "...") if len(s) > n else s


def result_label(r: dict) -> str:
    if r["status"] == "pass":
        return "PASS"
    if r["status"] == "fail":
        return "FAIL"
    # skipped
    if "notest" in (r.get("tags") or []):
        return "skip (notest)"
    return f"skip ({r['lang']} not runnable)"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=Path("report_run.json"))
    ap.add_argument("--docs", type=Path, default=Path("docs"))
    ap.add_argument("--out", type=Path, default=Path(".github/scripts/CODE_TEST_REPORT.md"))
    ap.add_argument("--dashboard", type=Path, default=None)
    args = ap.parse_args()

    records = json.loads(args.results.read_text(encoding="utf-8")) if args.results.exists() else []
    by_page: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        by_page[r["page"]].append(r)

    # Every page under docs (so 0-block pages are visible too)
    all_pages = sorted(
        p.as_posix() for p in (set(args.docs.rglob("*.mdx")) | set(args.docs.rglob("*.md")))
    )

    rows, details, tot = [], [], defaultdict(int)
    for page in all_pages:
        blocks = sorted(by_page.get(page, []), key=lambda r: r["block"])
        n_pass = sum(1 for r in blocks if r["status"] == "pass")
        n_fail = sum(1 for r in blocks if r["status"] == "fail")
        n_skip = sum(1 for r in blocks if r["status"] == "skipped")
        owner = resolve(Path(page))
        tot["pass"] += n_pass; tot["fail"] += n_fail; tot["skip"] += n_skip
        tot["blocks"] += len(blocks)

        if not blocks:
            status = "no code"
        elif n_fail:
            status = f"{n_fail} FAIL"
        elif n_pass:
            status = "all pass"
        else:
            status = "all skip"
        rel = page.split("docs/", 1)[-1]
        rows.append((rel, owner, len(blocks), n_pass, n_fail, n_skip, status))

        if blocks:
            details.append(f"\n### `{page}`  -  @{owner}  -  "
                           f"{n_pass} pass / {n_fail} fail / {n_skip} skip\n")
            details.append("| Block | Lang | Result | Detail |")
            details.append("|------:|------|--------|--------|")
            for r in blocks:
                details.append(f"| {r['block']} | {r['lang']} | {result_label(r)} | {clean(r['detail'])} |")

    pages_with = sum(1 for r in rows if r[2] > 0)
    pages_fail = sum(1 for r in rows if r[4] > 0)

    # ---- Summary table (markdown) ----
    summary = ["| Page | Owner | Blocks | Pass | Fail | Skip | Status |",
               "|------|-------|-------:|-----:|-----:|-----:|--------|"]
    for rel, owner, nb, np_, nf, ns, status in rows:
        summary.append(f"| {rel} | @{owner} | {nb} | {np_} | {nf} | {ns} | {status} |")
    summary_md = "\n".join(summary)

    header = (
        f"_Totals: {len(all_pages)} pages ({pages_with} with code, {pages_fail} with "
        f"failures) - {tot['blocks']} blocks: **{tot['pass']} pass**, "
        f"**{tot['fail']} fail**, {tot['skip']} skip._"
    )

    out = [
        "# Code-block test report (per page)",
        "",
        "Generated by `.github/scripts/report.py` from a full run of "
        "`extract_code_blocks.py --run`. Every runnable block is executed "
        "(test-by-default); `notest` and non-runnable languages (cpp, text, "
        "json, ...) show as `skip`.",
        "",
        header,
        "",
        "## Summary (every page)",
        "",
        summary_md,
        "",
        "## Per-page detail (pages with code blocks)",
        *details,
        "",
    ]
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {args.out} ({len(all_pages)} pages, {tot['blocks']} blocks).")

    # ---- Inject summary into a Mintlify page between markers ----
    if args.dashboard and args.dashboard.exists():
        text = args.dashboard.read_text(encoding="utf-8")
        block = "{/* RESULTS_START - generated by .github/scripts/report.py; do not edit by hand */}\n\n" + \
                header + "\n\n" + summary_md + "\n\n{/* RESULTS_END */}"
        new = re.sub(r"\{/\* RESULTS_START.*?\{/\* RESULTS_END \*/\}", lambda _m: block, text, flags=re.S)
        if new != text:
            args.dashboard.write_text(new, encoding="utf-8")
            print(f"Updated {args.dashboard} results table.")


if __name__ == "__main__":
    main()
