import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'welcome',
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: true,
      link: {type: 'doc', id: 'getting-started/index'},
      items: [
        'getting-started/installation',
        'getting-started/overview',
        'getting-started/quickstart',
        'getting-started/supported-hardware',
      ],
    },
    {
      type: 'category',
      label: '💻 Applications with Ryzen',
      collapsed: true,
      link: {type: 'doc', id: 'applications/index'},
      items: [],
    },
    {
      type: 'category',
      label: '🧠 Models & Tutorials',
      collapsed: true,
      link: {type: 'doc', id: 'models-tutorials/index'},
      items: [
        {
          type: 'category',
          label: 'Audio',
          collapsed: true,
          link: {type: 'doc', id: 'models-tutorials/audio/index'},
          items: [
            'models-tutorials/audio/whisper/index',
          ],
        },
        {
          type: 'category',
          label: 'Large Language Models',
          collapsed: true,
          link: {type: 'doc', id: 'models-tutorials/llms/overview'},
          items: [
            'models-tutorials/nlp/distilbert/index',
            'models-tutorials/llms/hybrid-inference',
            'models-tutorials/llms/linux-setup',
            'models-tutorials/llms/llm-sft-deploy/index',
            'models-tutorials/llms/oga-api/index',
            'models-tutorials/llms/oga-inference/index',
            'models-tutorials/llms/python-api',
            'models-tutorials/llms/rag-oga/index',
            'models-tutorials/llms/server-interface',
            'models-tutorials/llms/vlm/index',
          ],
        },
        {
          type: 'category',
          label: 'Multimodal',
          collapsed: true,
          link: {type: 'doc', id: 'models-tutorials/multimodal/index'},
          items: [
            'models-tutorials/multimodal/npu-gpu-pipeline/index',
          ],
        },
        {
          type: 'category',
          label: 'Vision',
          collapsed: true,
          link: {type: 'doc', id: 'models-tutorials/vision/index'},
          items: [
            'models-tutorials/vision/cnn-examples',
            'models-tutorials/vision/getting-started-resnet/bf16/cpp-deployment',
            'models-tutorials/vision/getting-started-resnet/bf16/index',
            'models-tutorials/vision/hello-world/index',
            'models-tutorials/vision/igpu-getting-started/index',
            'models-tutorials/vision/image-classification/index',
            'models-tutorials/vision/object-detection/yolov8m/index',
            'models-tutorials/vision/object-detection/yolov8s-worldv2/index',
            'models-tutorials/vision/stable-diffusion',
            'models-tutorials/vision/super-resolution/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Tools',
      collapsed: true,
      link: {type: 'doc', id: 'develop/index'},
      items: [
        'develop/app-development',
        'develop/cvml-library',
        'develop/model-deployment',
        'develop/model-quantization',
        'develop/onnx-model-preparation',
        'develop/operator-preparation',
        'develop/rocm-client-gpu',
        'models-tutorials/vision/cvml/index',
        'models-tutorials/vision/quark-quantization/index',
        'models-tutorials/vision/quark-quantization/advanced',
        'models-tutorials/vision/torchvision-inference/index',
        'tools/ai-analyzer',
        'tools/benchmarking/index',
        'tools/npu-check/index',
        'tools/npu-management',
      ],
    },
    {
      type: 'category',
      label: '📖 Reference',
      collapsed: true,
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/changelog/index',
        'reference/licenses',
        'reference/model-list',
        'reference/supported-operators',
      ],
    },
  ],
};

export default sidebars;
